<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Key Presses_target</name>
   <tag></tag>
   <elementGuidId>deed7323-8147-4ed9-9346-747cf088f99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='target']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f89beda-c0b9-4389-ace8-5690831433b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target</value>
      <webElementGuid>3cebc021-d40d-4116-a434-20a2992b6498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26e7e898-b9bd-46c7-9e59-d6fba27541f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target&quot;)</value>
      <webElementGuid>5e798e35-cd85-485a-9702-b9fe929de19c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='target']</value>
      <webElementGuid>c9d4b545-6619-406b-8a5a-4417616109d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/form/input</value>
      <webElementGuid>a0635cb6-09d8-44fd-9c15-000f15aa9fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c6c2ef4c-876d-47b7-a6fa-02e6f9d61946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'target' and @type = 'text']</value>
      <webElementGuid>2ece579c-c76f-4e02-b033-a403ce814900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
